sudo: required
language: generic
services:
  - docker
env:
  - PYTHON_IMAGE="python:3.6"
  - PYTHON_IMAGE="python:3.7-rc"

script:
  - ./ci/run_tests_in_docker.sh $PYTHON_IMAGE

deploy:
  provider: pypi
  user: "$TWINE_USER"
  password: "$TWINE_PASSWORD"
  distributions: "sdist bdist_wheel"
  on:
    tags: true
