name: CI

on: [push]

jobs:
  build_and_test_pinned:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.8', '3.9']  # 'pypy-3.7'
        backend: [asyncio, trio, uvloop]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements_test.txt'
      - run: pip install . -r requirements_test.txt
      - run: PURERPC_BACKEND=${{ matrix.backend }} pytest

  build_and_test_latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.10']
        backend: [asyncio, trio, uvloop]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install .[test]
      - run: PURERPC_BACKEND=${{ matrix.backend }} pytest

  build_and_test_pypy:
    if: ${{ false }}  # install for pypy is too slow due to grpc packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['pypy-3.7']
        backend: [asyncio]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements_test_pypy.txt'
      - run: pip install . -r requirements_test_pypy.txt
      - run: PURERPC_BACKEND=${{ matrix.backend }} pytest
